import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Sidebar from "./_components/Sidebar/Sidebar";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "./_components/Header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <div className=" absolute left-0 top-0 bottom-0 w-72 bg-blue-300">
            <Sidebar />
          </div>
          <div className=" absolute left-72 top-0 h-28 right-0 bg-blue-300">
            <Header />
          </div>
          <div className="pl-72">
            {children}
          </div>
        </body>
      </html>
    </ClerkProvider>

  );
}
